// Automatically generated by MockGen. DO NOT EDIT!

package client

import (
	context "context"

	gomock "github.com/golang/mock/gomock"

	"github.com/qiwitech/qdp/proto/apipb"
)

// Mock of APIServiceInterface interface
type MockAPIServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockAPIServiceInterfaceRecorder
}

// Recorder for MockAPIServiceInterface (not exported)
type _MockAPIServiceInterfaceRecorder struct {
	mock *MockAPIServiceInterface
}

func NewMockAPIServiceInterface(ctrl *gomock.Controller) *MockAPIServiceInterface {
	mock := &MockAPIServiceInterface{ctrl: ctrl}
	mock.recorder = &_MockAPIServiceInterfaceRecorder{mock}
	return mock
}

func (_m *MockAPIServiceInterface) EXPECT() *_MockAPIServiceInterfaceRecorder {
	return _m.recorder
}

func (_m *MockAPIServiceInterface) GetBalance(_param0 context.Context, _param1 *apipb.GetBalanceRequest) (*apipb.GetBalanceResponse, error) {
	ret := _m.ctrl.Call(_m, "GetBalance", _param0, _param1)
	ret0, _ := ret[0].(*apipb.GetBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) GetBalance(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetBalance", arg0, arg1)
}

func (_m *MockAPIServiceInterface) GetByMetaKey(_param0 context.Context, _param1 *apipb.GetByMetaKeyRequest) (*apipb.GetByMetaKeyResponse, error) {
	ret := _m.ctrl.Call(_m, "GetByMetaKey", _param0, _param1)
	ret0, _ := ret[0].(*apipb.GetByMetaKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) GetByMetaKey(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetByMetaKey", arg0, arg1)
}

func (_m *MockAPIServiceInterface) GetHistory(_param0 context.Context, _param1 *apipb.GetHistoryRequest) (*apipb.GetHistoryResponse, error) {
	ret := _m.ctrl.Call(_m, "GetHistory", _param0, _param1)
	ret0, _ := ret[0].(*apipb.GetHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) GetHistory(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHistory", arg0, arg1)
}

func (_m *MockAPIServiceInterface) GetLastSettings(_param0 context.Context, _param1 *apipb.GetLastSettingsRequest) (*apipb.GetLastSettingsResponse, error) {
	ret := _m.ctrl.Call(_m, "GetLastSettings", _param0, _param1)
	ret0, _ := ret[0].(*apipb.GetLastSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) GetLastSettings(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLastSettings", arg0, arg1)
}

func (_m *MockAPIServiceInterface) GetPrevHash(_param0 context.Context, _param1 *apipb.GetPrevHashRequest) (*apipb.GetPrevHashResponse, error) {
	ret := _m.ctrl.Call(_m, "GetPrevHash", _param0, _param1)
	ret0, _ := ret[0].(*apipb.GetPrevHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) GetPrevHash(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPrevHash", arg0, arg1)
}

func (_m *MockAPIServiceInterface) ProcessTransfer(_param0 context.Context, _param1 *apipb.TransferRequest) (*apipb.TransferResponse, error) {
	ret := _m.ctrl.Call(_m, "ProcessTransfer", _param0, _param1)
	ret0, _ := ret[0].(*apipb.TransferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) ProcessTransfer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ProcessTransfer", arg0, arg1)
}

func (_m *MockAPIServiceInterface) PutMeta(_param0 context.Context, _param1 *apipb.PutMetaRequest) (*apipb.PutMetaResponse, error) {
	ret := _m.ctrl.Call(_m, "PutMeta", _param0, _param1)
	ret0, _ := ret[0].(*apipb.PutMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) PutMeta(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutMeta", arg0, arg1)
}

func (_m *MockAPIServiceInterface) SearchMeta(_param0 context.Context, _param1 *apipb.SearchMetaRequest) (*apipb.SearchMetaResponse, error) {
	ret := _m.ctrl.Call(_m, "SearchMeta", _param0, _param1)
	ret0, _ := ret[0].(*apipb.SearchMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) SearchMeta(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SearchMeta", arg0, arg1)
}

func (_m *MockAPIServiceInterface) UpdateSettings(_param0 context.Context, _param1 *apipb.SettingsRequest) (*apipb.SettingsResponse, error) {
	ret := _m.ctrl.Call(_m, "UpdateSettings", _param0, _param1)
	ret0, _ := ret[0].(*apipb.SettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIServiceInterfaceRecorder) UpdateSettings(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateSettings", arg0, arg1)
}
