// Code generated by "stringer -type Status ./archiver/"; DO NOT EDIT

package archiver

import "fmt"

const _Status_name = "NOTFOUNDUNPROCESSEDPREPROCESSEDFIXEDUPLOADED"

var _Status_index = [...]uint8{0, 8, 19, 31, 36, 44}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
