// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/qiwitech/qdp/proto/gatepb (interfaces: ProcessorServiceInterface)

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	gatepb "github.com/qiwitech/qdp/proto/gatepb"
)

// Mock of ProcessorServiceInterface interface
type MockProcessorServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockProcessorServiceInterfaceRecorder
}

// Recorder for MockProcessorServiceInterface (not exported)
type _MockProcessorServiceInterfaceRecorder struct {
	mock *MockProcessorServiceInterface
}

func NewMockProcessorServiceInterface(ctrl *gomock.Controller) *MockProcessorServiceInterface {
	mock := &MockProcessorServiceInterface{ctrl: ctrl}
	mock.recorder = &_MockProcessorServiceInterfaceRecorder{mock}
	return mock
}

func (_m *MockProcessorServiceInterface) EXPECT() *_MockProcessorServiceInterfaceRecorder {
	return _m.recorder
}

func (_m *MockProcessorServiceInterface) GetBalance(_param0 context.Context, _param1 *gatepb.GetBalanceRequest) (*gatepb.GetBalanceResponse, error) {
	ret := _m.ctrl.Call(_m, "GetBalance", _param0, _param1)
	ret0, _ := ret[0].(*gatepb.GetBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProcessorServiceInterfaceRecorder) GetBalance(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetBalance", arg0, arg1)
}

func (_m *MockProcessorServiceInterface) GetLastSettings(_param0 context.Context, _param1 *gatepb.GetLastSettingsRequest) (*gatepb.GetLastSettingsResponse, error) {
	ret := _m.ctrl.Call(_m, "GetLastSettings", _param0, _param1)
	ret0, _ := ret[0].(*gatepb.GetLastSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProcessorServiceInterfaceRecorder) GetLastSettings(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLastSettings", arg0, arg1)
}

func (_m *MockProcessorServiceInterface) GetPrevHash(_param0 context.Context, _param1 *gatepb.GetPrevHashRequest) (*gatepb.GetPrevHashResponse, error) {
	ret := _m.ctrl.Call(_m, "GetPrevHash", _param0, _param1)
	ret0, _ := ret[0].(*gatepb.GetPrevHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProcessorServiceInterfaceRecorder) GetPrevHash(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPrevHash", arg0, arg1)
}

func (_m *MockProcessorServiceInterface) ProcessTransfer(_param0 context.Context, _param1 *gatepb.TransferRequest) (*gatepb.TransferResponse, error) {
	ret := _m.ctrl.Call(_m, "ProcessTransfer", _param0, _param1)
	ret0, _ := ret[0].(*gatepb.TransferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProcessorServiceInterfaceRecorder) ProcessTransfer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ProcessTransfer", arg0, arg1)
}

func (_m *MockProcessorServiceInterface) UpdateSettings(_param0 context.Context, _param1 *gatepb.SettingsRequest) (*gatepb.SettingsResponse, error) {
	ret := _m.ctrl.Call(_m, "UpdateSettings", _param0, _param1)
	ret0, _ := ret[0].(*gatepb.SettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProcessorServiceInterfaceRecorder) UpdateSettings(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateSettings", arg0, arg1)
}
