// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/qiwitech/qdp/proto/plutodbpb (interfaces: PlutoDBServiceInterface)

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	plutodbpb "github.com/qiwitech/qdp/proto/plutodbpb"
)

// Mock of PlutoDBServiceInterface interface
type MockPlutoDBServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockPlutoDBServiceInterfaceRecorder
}

// Recorder for MockPlutoDBServiceInterface (not exported)
type _MockPlutoDBServiceInterfaceRecorder struct {
	mock *MockPlutoDBServiceInterface
}

func NewMockPlutoDBServiceInterface(ctrl *gomock.Controller) *MockPlutoDBServiceInterface {
	mock := &MockPlutoDBServiceInterface{ctrl: ctrl}
	mock.recorder = &_MockPlutoDBServiceInterfaceRecorder{mock}
	return mock
}

func (_m *MockPlutoDBServiceInterface) EXPECT() *_MockPlutoDBServiceInterfaceRecorder {
	return _m.recorder
}

func (_m *MockPlutoDBServiceInterface) Fetch(_param0 context.Context, _param1 *plutodbpb.FetchRequest) (*plutodbpb.FetchResponse, error) {
	ret := _m.ctrl.Call(_m, "Fetch", _param0, _param1)
	ret0, _ := ret[0].(*plutodbpb.FetchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlutoDBServiceInterfaceRecorder) Fetch(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fetch", arg0, arg1)
}

func (_m *MockPlutoDBServiceInterface) GetHistory(_param0 context.Context, _param1 *plutodbpb.GetHistoryRequest) (*plutodbpb.GetHistoryResponse, error) {
	ret := _m.ctrl.Call(_m, "GetHistory", _param0, _param1)
	ret0, _ := ret[0].(*plutodbpb.GetHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlutoDBServiceInterfaceRecorder) GetHistory(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHistory", arg0, arg1)
}

func (_m *MockPlutoDBServiceInterface) GetTxnMulti(_param0 context.Context, _param1 *plutodbpb.GetTxnMultiRequest) (*plutodbpb.GetTxnMultiResponse, error) {
	ret := _m.ctrl.Call(_m, "GetTxnMulti", _param0, _param1)
	ret0, _ := ret[0].(*plutodbpb.GetTxnMultiResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlutoDBServiceInterfaceRecorder) GetTxnMulti(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetTxnMulti", arg0, arg1)
}
