// Code generated by protoc-gen-gogo.
// source: pusher_service.proto
// DO NOT EDIT!

/*
Package pusherpb is a generated protocol buffer package.

Pusher API

It is generated from these files:
	pusher_service.proto

It has these top-level messages:
	Status
	PushRequest
	PushResponse
	PushSettingsRequest
	PushSettingsResponse
*/
package pusherpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import chain "github.com/qiwitech/qdp/proto/chainpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PushCode int32

const (
	PushCode_OK             PushCode = 0
	PushCode_INTERNAL_ERROR PushCode = 1
)

var PushCode_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
}
var PushCode_value = map[string]int32{
	"OK":             0,
	"INTERNAL_ERROR": 1,
}

func (x PushCode) String() string {
	return proto.EnumName(PushCode_name, int32(x))
}
func (PushCode) EnumDescriptor() ([]byte, []int) { return fileDescriptorPusherService, []int{0} }

type Status struct {
	// A simple error code that can be easily handled by the client.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing human-readable error message in English. It should
	// both explain the error and offer an actionable resolution to it.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptorPusherService, []int{0} }

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PushRequest struct {
	Txns []*chain.Txn `protobuf:"bytes,1,rep,name=txns" json:"txns,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptorPusherService, []int{1} }

func (m *PushRequest) GetTxns() []*chain.Txn {
	if m != nil {
		return m.Txns
	}
	return nil
}

type PushResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptorPusherService, []int{2} }

func (m *PushResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type PushSettingsRequest struct {
	Settings []*chain.Settings `protobuf:"bytes,1,rep,name=settings" json:"settings,omitempty"`
}

func (m *PushSettingsRequest) Reset()                    { *m = PushSettingsRequest{} }
func (m *PushSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*PushSettingsRequest) ProtoMessage()               {}
func (*PushSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptorPusherService, []int{3} }

func (m *PushSettingsRequest) GetSettings() []*chain.Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type PushSettingsResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PushSettingsResponse) Reset()         { *m = PushSettingsResponse{} }
func (m *PushSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*PushSettingsResponse) ProtoMessage()    {}
func (*PushSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorPusherService, []int{4}
}

func (m *PushSettingsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "pusher.Status")
	proto.RegisterType((*PushRequest)(nil), "pusher.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "pusher.PushResponse")
	proto.RegisterType((*PushSettingsRequest)(nil), "pusher.PushSettingsRequest")
	proto.RegisterType((*PushSettingsResponse)(nil), "pusher.PushSettingsResponse")
	proto.RegisterEnum("pusher.PushCode", PushCode_name, PushCode_value)
}

func init() { proto.RegisterFile("pusher_service.proto", fileDescriptorPusherService) }

var fileDescriptorPusherService = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x4f, 0xe2, 0x40,
	0x14, 0xde, 0xb2, 0x6c, 0x97, 0x7d, 0xac, 0x48, 0x06, 0x4c, 0x1a, 0x34, 0x86, 0xf4, 0x40, 0x88,
	0xc6, 0x36, 0xd6, 0xc8, 0xd1, 0x44, 0x0c, 0x07, 0xa2, 0x01, 0x32, 0x70, 0xf2, 0x42, 0xda, 0x32,
	0xd2, 0x46, 0x99, 0xa9, 0x7d, 0x53, 0xc3, 0x9f, 0x6f, 0x3a, 0xd3, 0x12, 0x30, 0x5e, 0x3c, 0xb5,
	0xfd, 0xde, 0xfb, 0x7e, 0xf4, 0x9b, 0x81, 0x76, 0x92, 0x61, 0xc4, 0xd2, 0x25, 0xb2, 0xf4, 0x23,
	0x0e, 0x99, 0x93, 0xa4, 0x42, 0x0a, 0x62, 0x6a, 0xb4, 0x73, 0xbb, 0x8e, 0x65, 0x94, 0x05, 0x4e,
	0x28, 0x36, 0x2e, 0x8f, 0x5f, 0x7d, 0xbe, 0x7a, 0x11, 0xa9, 0x9b, 0xbc, 0x65, 0x52, 0xa0, 0xab,
	0x56, 0xdd, 0x30, 0xf2, 0x63, 0x9e, 0x04, 0xfa, 0xa9, 0xe9, 0xf6, 0x00, 0xcc, 0xb9, 0xf4, 0x65,
	0x86, 0x84, 0x40, 0x35, 0x14, 0x2b, 0x66, 0x19, 0x5d, 0xa3, 0xff, 0x87, 0xaa, 0x77, 0x62, 0xc1,
	0xdf, 0x0d, 0x43, 0xf4, 0xd7, 0xcc, 0xaa, 0x74, 0x8d, 0xfe, 0x3f, 0x5a, 0x7e, 0xda, 0x57, 0x50,
	0x9f, 0x65, 0x18, 0x51, 0xf6, 0x9e, 0x31, 0x94, 0xe4, 0x1c, 0xaa, 0x72, 0xcb, 0xd1, 0x32, 0xba,
	0xbf, 0xfb, 0x75, 0x0f, 0x1c, 0x6d, 0xb1, 0xd8, 0x72, 0xaa, 0x70, 0x7b, 0x00, 0xff, 0xf5, 0x3a,
	0x26, 0x82, 0x23, 0x23, 0x3d, 0x30, 0x51, 0xd9, 0x2a, 0xbb, 0xba, 0xd7, 0x70, 0xf4, 0x6f, 0x38,
	0x3a, 0x0c, 0x2d, 0xa6, 0xf6, 0x10, 0x5a, 0x39, 0x6f, 0xce, 0xa4, 0x8c, 0xf9, 0x1a, 0x4b, 0xbb,
	0x4b, 0xa8, 0x61, 0x01, 0x15, 0x96, 0xc7, 0x85, 0xe5, 0x6e, 0x73, 0xb7, 0x60, 0xdf, 0x41, 0xfb,
	0x50, 0xe3, 0x67, 0x19, 0x2e, 0x7a, 0x50, 0xcb, 0xf9, 0x0f, 0x79, 0x21, 0x26, 0x54, 0xa6, 0x8f,
	0xcd, 0x5f, 0x84, 0x40, 0x63, 0x3c, 0x59, 0x8c, 0xe8, 0xe4, 0xfe, 0x69, 0x39, 0xa2, 0x74, 0x4a,
	0x9b, 0x86, 0x37, 0x84, 0xa3, 0x99, 0x12, 0x98, 0xeb, 0x03, 0x22, 0xd7, 0x50, 0xcd, 0x01, 0xd2,
	0x2a, 0x85, 0xf7, 0x1a, 0xeb, 0xb4, 0x0f, 0x41, 0x9d, 0xc9, 0x0b, 0xe0, 0xa4, 0xcc, 0x79, 0xa8,
	0x35, 0xd6, 0x05, 0x96, 0x43, 0x72, 0xba, 0x4f, 0xff, 0x52, 0x4f, 0xe7, 0xec, 0xfb, 0xa1, 0xf6,
	0x18, 0xc2, 0x73, 0x4d, 0x8f, 0x93, 0x20, 0x30, 0xd5, 0x2d, 0xb8, 0xf9, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xc7, 0xca, 0xec, 0x5c, 0x02, 0x00, 0x00,
}
